export const FILTER_OPTIONS = {
  isAll: true,
  petTypeId: 0,
  petName: "",
  size: "",
  minAge: 0,
  maxAge: 0,
  gender: 0,
  minWeight: 0,
  maxWeight: 0,
  breedId: 0,
  pageNumber:1,
  pageSize:10,
  totalPets:0,
};
