export const CitiesOptions = [
  { value: "Baku", label: "Baku" },
  { value: "Ganja", label: "Ganja" },
  { value: "Sumqayit", label: "Sumqayit" },
  { value: "Mingachevir", label: "Mingachevir" },
  { value: "Lankaran", label: "Lankaran" },
  { value: "Shirvan", label: "Shirvan" },
  { value: "Nakhchivan", label: "Nakhchivan" },
  { value: "Shaki", label: "Shaki" },
  { value: "Yevlakh", label: "Yevlakh" },
  { value: "Khirdalan", label: "Khirdalan" },
  { value: "Shamakhi", label: "Shamakhi" },
  { value: "Naftalan", label: "Naftalan" },
  { value: "Quba", label: "Quba" },
  { value: "Qusar", label: "Qusar" },
  { value: "Goychay", label: "Goychay" },
  { value: "Zaqatala", label: "Zaqatala" },
  { value: "Gabala", label: "Gabala" },
  { value: "Sabirabad", label: "Sabirabad" },
  { value: "Agdam", label: "Agdam" },
  { value: "Jalilabad", label: "Jalilabad" },
  { value: "Fuzuli", label: "Fuzuli" },
  { value: "Khachmaz", label: "Khachmaz" },
  { value: "Imishli", label: "Imishli" },
  { value: "Saatli", label: "Saatli" },
  { value: "Salyan", label: "Salyan" },
  { value: "Shabran", label: "Shabran" },
  { value: "Shamkir", label: "Shamkir" },
  { value: "Tovuz", label: "Tovuz" },
  { value: "Zardab", label: "Zardab" },
];

export const petTypesOptions = [
  { label: "Dogs", value: 1 },
  { label: "Cats", value: 2 },
  { label: "Birds", value: 3 },
  { label: "Reptiles", value: 4 },
  { label: "Rodents", value: 5 },
  { label: "Fish", value: 6 },
  { label: "Farm Animals", value: 7 },
  { label: "Exotic Pets", value: 8 },
];
